"""
AST / Token-based Lua Code Optimizer Engine Module.

Performs:
1. Safe constant arithmetic folding (integers, hex, floats, basic ops)
2. String and comment preservation (never mutates literals)
3. Dead self-assignment removal (var = var)
4. Local variable alias/copy propagation
5. Code cleanup and normalization
"""

from __future__ import annotations

from typing import List, Tuple, Optional, Dict, Union
import ast
import re
import uuid
import functools
from .lua_lexer import tokenize_lua_chunks, join_lua_tokens

split_lua_tokens = tokenize_lua_chunks


HEX_INT_PATTERN = re.compile(r"^0[xX][0-9a-fA-F]+$")
BIN_INT_PATTERN = re.compile(r"^0[bB][01]+$")
STANDALONE_HEX_PATTERN = re.compile(r"\b0[xX]([0-9a-fA-F]+)\b")
STANDALONE_BIN_PATTERN = re.compile(r"\b0[bB]([01]+)\b")

# Matches parenthesized or standalone constant arithmetic expressions like:
# (-80732 + 80796), (0x497e0 + -301009), (1e5 + 20), (2 ^ 8)
MATH_EXPR_PATTERN = re.compile(
    r"\(\s*(-?(?:0[xX][0-9a-fA-F]+|0[bB][01]+|\d+(?:\.\d+)?(?:[eE][+-]?\d+)?))\s*([+\-*%^])\s*(-?(?:0[xX][0-9a-fA-F]+|0[bB][01]+|\d+(?:\.\d+)?(?:[eE][+-]?\d+)?|\(-?\d+\)))\s*\)"
)
PAREN_LITERAL_PATTERN = re.compile(
    r"\(\s*(-?(?:0[xX][0-9a-fA-F]+|0[bB][01]+|\d+(?:\.\d+)?(?:[eE][+-]?\d+)?))\s*\)"
)
DOUBLE_NEG_PATTERN = re.compile(r"-\s*\(\s*-\s*([0-9a-zA-Z_]+)\s*\)")
_RE_IDENT = re.compile(r"[a-zA-Z_][a-zA-Z0-9_]*")


@functools.lru_cache(maxsize=8192)
def _get_alias_sub_pattern(var_name: str) -> re.Pattern:
    return re.compile(rf"(?<![.:])\b{re.escape(var_name)}\b")


def parse_lua_string_token(token_type: str, lit: str) -> Optional[str]:
    """Parse a Lua string token into its unescaped raw string content."""
    if token_type == "STRING_LONG":
        m = re.match(r"^\[(=*)\[(.*)\]\1\]$", lit, re.DOTALL)
        if m:
            return m.group(2)
        if lit.startswith("[[") and lit.endswith("]]"):
            return lit[2:-2]
    if token_type == "STRING_SHORT" and len(lit) >= 2:
        inner = lit[1:-1]

        def replace_decimal(m):
            return chr(int(m.group(1)))

        def replace_hex(m):
            return chr(int(m.group(1), 16))

        s = re.sub(r"\\([0-9]{1,3})", replace_decimal, inner)
        s = re.sub(r"\\x([0-9a-fA-F]{2})", replace_hex, s)
        s = s.replace(r"\n", "\n").replace(r"\r", "\r").replace(r"\t", "\t")
        s = s.replace(r"\\", "\\").replace(r'\"', '"').replace(r"\'", "'")
        return s
    return None


def escape_for_lua_literal(s: str) -> str:
    """Format string content safely back into a Lua double-quoted string literal."""
    parts = ['"']
    for ch in s:
        b = ord(ch)
        if ch == "\\":
            parts.append(r"\\")
        elif ch == '"':
            parts.append(r'\"')
        elif ch == "\n":
            parts.append(r"\n")
        elif ch == "\r":
            parts.append(r"\r")
        elif ch == "\t":
            parts.append(r"\t")
        elif 32 <= b <= 126:
            parts.append(ch)
        else:
            parts.append(f"\\{b:03d}")
    parts.append('"')
    return "".join(parts)


def fold_string_concat_tokens(tokens: List[Tuple[str, str]]) -> List[Tuple[str, str]]:
    """
    Fold adjacent string literal concatenations generated by Prometheus SplitStrings.lua:
        "part1" .. "part2" -> "part1part2"
    """
    i = 0
    res: List[Tuple[str, str]] = []
    while i < len(tokens):
        if (
            tokens[i][0] in ("STRING_SHORT", "STRING_LONG")
            and i + 2 < len(tokens)
            and tokens[i + 1][0] == "CODE"
            and tokens[i + 1][1].strip() == ".."
            and tokens[i + 2][0] in ("STRING_SHORT", "STRING_LONG")
        ):
            s1 = parse_lua_string_token(tokens[i][0], tokens[i][1])
            s2 = parse_lua_string_token(tokens[i + 2][0], tokens[i + 2][1])
            if s1 is not None and s2 is not None:
                combined = escape_for_lua_literal(s1 + s2)
                tokens[i + 2] = ("STRING_SHORT", combined)
                i += 2
                continue
        res.append(tokens[i])
        i += 1
    return res


def fold_table_concat_calls(
    code: str,
    mapping: Optional[Dict[str, str]] = None,
    prefix: str = "",
) -> str:
    """
    Fold static table.concat({"part1", "part2", ...}) calls into a single string literal.
    When mapping and prefix are provided, operates safely on masked string placeholders.
    """
    if mapping is not None and prefix:
        pattern = re.compile(
            rf'\btable\.concat\s*\(\s*\{{\s*([^{{}}]+?)\s*\}}\s*(?:,\s*({prefix}STR_\d+__|["\'][^"\']*["\']))?\s*\)'
        )

        def repl_masked(m):
            raw_items = m.group(1)
            sep_token = m.group(2)
            sep = ""
            if sep_token:
                if sep_token in mapping:
                    raw_sep = parse_lua_string_token("STRING_SHORT", mapping[sep_token])
                    if raw_sep is None:
                        raw_sep = parse_lua_string_token("STRING_LONG", mapping[sep_token])
                    sep = raw_sep or ""
                else:
                    sep = sep_token.strip("'\"")

            placeholders = re.findall(rf'{prefix}STR_\d+__', raw_items)
            if placeholders:
                parts = []
                for ph in placeholders:
                    if ph in mapping:
                        raw_str = parse_lua_string_token("STRING_SHORT", mapping[ph])
                        if raw_str is None:
                            raw_str = parse_lua_string_token("STRING_LONG", mapping[ph])
                        if raw_str is not None:
                            parts.append(raw_str)
                        else:
                            return m.group(0)
                    else:
                        return m.group(0)
                joined = sep.join(parts)
                new_lit = escape_for_lua_literal(joined)
                new_ph = f"{prefix}STR_{len(mapping)}__"
                mapping[new_ph] = new_lit
                return new_ph
            return m.group(0)

        return pattern.sub(repl_masked, code)

    pattern = re.compile(
        r'\btable\.concat\s*\(\s*\{\s*([^}]+?)\s*\}\s*(?:,\s*["\']([^"\']*)["\'])?\s*\)'
    )

    def repl(m):
        raw_items = m.group(1)
        sep = m.group(2) if m.group(2) is not None else ""
        strings = re.findall(r'["\']([^"\']*)["\']', raw_items)
        if strings:
            joined = sep.join(strings)
            return escape_for_lua_literal(joined)
        return m.group(0)

    return pattern.sub(repl, code)


def strip_prometheus_watermarks(
    code: str,
    mapping: Optional[Dict[str, str]] = None,
    prefix: str = "",
) -> str:
    """
    Detect and strip Prometheus WatermarkCheck step dead branches:
        if _var ~= "This Script is Part of the Prometheus Obfuscator by levno-710" then return end
    """
    if mapping is not None and prefix:
        pattern = re.compile(
            rf'if\s+\(?[a-zA-Z0-9_]+\s*~=\s*({prefix}STR_\d+__)\)?\s+then\s+return\s+end;?',
            re.IGNORECASE,
        )

        def wm_repl(m):
            ph = m.group(1)
            if ph in mapping and "Prometheus" in mapping[ph]:
                return "-- [Epimetheus: Stripped Prometheus watermark check]"
            return m.group(0)

        return pattern.sub(wm_repl, code)

    pattern = re.compile(
        r"if\s+\(?[a-zA-Z0-9_]+\s*~=\s*[\"'].*?Prometheus.*?[\"']\)?\s+then\s+return\s+end;?",
        re.IGNORECASE,
    )
    return pattern.sub("-- [Epimetheus: Stripped Prometheus watermark check]", code)


_SIMPLE_BINARY_EXPR = re.compile(
    r"^\s*(-?(?:0[xX][0-9a-fA-F]+|0[bB][01]+|\d+(?:\.\d+)?))\s*([+\-*%^])\s*(-?(?:0[xX][0-9a-fA-F]+|0[bB][01]+|\d+(?:\.\d+)?))\s*$"
)


@functools.lru_cache(maxsize=4096)
def safe_eval_math_expr(expr_str: str) -> Optional[Union[int, float]]:
    """
    Safely evaluate a mathematical expression containing only numbers and basic operators.
    Supports hex (0x...), binary (0b...), scientific notation, power (^), modulo (%).
    Returns None if expression is invalid or dangerous.
    """
    clean = expr_str.strip()

    m_simple = _SIMPLE_BINARY_EXPR.match(clean)
    if m_simple:
        l_str, op, r_str = m_simple.groups()
        try:
            l = int(l_str, 0) if not ("." in l_str) else float(l_str)
            r = int(r_str, 0) if not ("." in r_str) else float(r_str)
            res = None
            if op == "+":
                res = l + r
            elif op == "-":
                res = l - r
            elif op == "*":
                res = l * r
            elif op == "/":
                if r != 0:
                    res = l / r
            elif op == "%":
                if r != 0:
                    res = l % r
            elif op == "^":
                if 0 <= r <= 64 and abs(l) <= 1e9:
                    res = l ** r

            if res is not None:
                if isinstance(res, float) and res.is_integer() and abs(res) < 1e15:
                    return int(res)
                return res
        except Exception:
            pass

    # Replace 0x... and 0b... with decimal for Python eval
    def replace_hex(m):
        return str(int(m.group(0), 16))

    def replace_bin(m):
        return str(int(m.group(0), 2))

    clean = STANDALONE_HEX_PATTERN.sub(replace_hex, clean)
    clean = STANDALONE_BIN_PATTERN.sub(replace_bin, clean)

    # Convert Lua power operator (^) to Python (**)
    clean = re.sub(r"(?<=\d|\))\s*\^\s*", " ** ", clean)

    try:
        parsed = ast.parse(clean, mode="eval")
    except Exception:
        return None

    for node in ast.walk(parsed):
        if not isinstance(
            node,
            (
                ast.Expression,
                ast.UnaryOp,
                ast.BinOp,
                ast.Constant,
                ast.USub,
                ast.UAdd,
                ast.Add,
                ast.Sub,
                ast.Mult,
                ast.Div,
                ast.Mod,
                ast.Pow,
                ast.FloorDiv,
            ),
        ):
            return None

        # Guard against huge exponent DoS (e.g. 9 ^ 999999999)
        if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Pow):
            if isinstance(node.right, ast.Constant):
                if not isinstance(node.right.value, (int, float)) or not (0 <= node.right.value <= 64):
                    return None
            else:
                return None
            if isinstance(node.left, ast.Constant) and isinstance(node.left.value, (int, float)):
                if abs(node.left.value) > 1e9:
                    return None

    try:
        val = eval(compile(parsed, "<string>", "eval"), {"__builtins__": None}, {})
        if isinstance(val, (int, float)):
            # If float is virtually an integer, convert to int
            if isinstance(val, float) and val.is_integer() and abs(val) < 1e15:
                return int(val)
            return val
    except Exception:
        return None

    return None


class AstOptimizer:
    """
    Lua source code post-processing optimizer.
    """

    def __init__(
        self,
        fold_constants: bool = True,
        fold_strings: bool = True,
        strip_watermarks: bool = True,
        propagate_copies: bool = True,
        eliminate_dead_assignments: bool = True,
    ):
        self.fold_constants = fold_constants
        self.fold_strings = fold_strings
        self.strip_watermarks = strip_watermarks
        self.propagate_copies = propagate_copies
        self.eliminate_dead_assignments = eliminate_dead_assignments

    def fold_math_expressions(self, code_chunk: str) -> str:
        """
        Recursively fold simple parenthesized arithmetic expressions, parenthesized literals,
        and double negations in a code chunk.
        """
        result = code_chunk

        # Pass 1: Parenthesized expressions
        def repl_math(m):
            nonlocal modified
            expr_text = m.group(0)
            inner = expr_text.strip("()")
            evaluated = safe_eval_math_expr(inner)
            if evaluated is not None:
                modified = True
                return str(evaluated)
            return expr_text

        for _ in range(8):
            modified = False
            result = MATH_EXPR_PATTERN.sub(repl_math, result)
            if not modified:
                break

        # Pass 2: Double negations: -(-x) -> x
        result = DOUBLE_NEG_PATTERN.sub(r"\1", result)

        # Pass 3: Parenthesized simple literals: (123) -> 123, (0x10) -> 16
        def repl_lit(m):
            nonlocal modified
            expr_text = m.group(0)
            inner = expr_text.strip("()")
            evaluated = safe_eval_math_expr(inner)
            if evaluated is not None:
                modified = True
                return str(evaluated)
            return expr_text

        for _ in range(3):
            modified = False
            result = PAREN_LITERAL_PATTERN.sub(repl_lit, result)
            if not modified:
                break

        return result

    def optimize_code_chunk(self, chunk: str) -> str:
        """
        Apply code-level transformations to non-string, non-comment Lua tokens.
        """
        if self.fold_constants:
            chunk = self.fold_math_expressions(chunk)

        return chunk

    def propagate_copy_assignments(self, lines: List[str]) -> List[str]:
        """
        Eliminate redundant aliases:
            local var_B = var_A
        where var_B is purely an immutable alias for var_A.
        Guarantees that:
        1. Chained aliases (local b = a; local c = b) resolve to their canonical root (a).
        2. Variables that are mutated or reassigned anywhere in the chunk are NEVER propagated,
           preserving exact program semantics and variable values.
        3. Object fields (obj.alias, obj:alias) are never mutated.
        """
        cleaned_lines: List[str] = []

        copy_pattern = re.compile(r"^\s*local\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*$")
        self_assign_pattern = re.compile(r"^\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*\1\s*$")
        lhs_assign_pattern = re.compile(r"^\s*(?:local\s+)?([a-zA-Z_][a-zA-Z0-9_]*)\s*=(?!=)")
        LUA_KEYWORDS = {"true", "false", "nil", "function", "return", "end", "not", "and", "or"}

        # Pass 1: Count LHS assignments per variable to determine mutability
        assignment_counts: Dict[str, int] = {}
        for line in lines:
            stripped = line.strip()
            if self.eliminate_dead_assignments and self_assign_pattern.match(stripped):
                continue
            m = lhs_assign_pattern.match(stripped)
            if m:
                var = m.group(1)
                assignment_counts[var] = assignment_counts.get(var, 0) + 1

        scope_stack: List[Dict[str, Any]] = [{"aliases": {}, "locals": set()}]

        def resolve_root(var: str) -> str:
            visited = set()
            curr = var
            while True:
                found = False
                for s in reversed(scope_stack):
                    if curr in s["aliases"]:
                        if curr in visited:
                            break
                        visited.add(curr)
                        curr = s["aliases"][curr]
                        found = True
                        break
                if not found:
                    break
            return curr

        active_aliases: Dict[str, str] = {}
        aliases_dirty = True

        def rebuild_active_aliases() -> None:
            nonlocal active_aliases, aliases_dirty
            active: Dict[str, str] = {}
            for i, s in enumerate(scope_stack):
                for dst, src in s["aliases"].items():
                    shadowed = False
                    for child_s in scope_stack[i + 1:]:
                        if src in child_s["locals"] or dst in child_s["locals"]:
                            shadowed = True
                            break
                    if not shadowed:
                        active[dst] = src
            active_aliases = active
            aliases_dirty = False

        for line in lines:
            stripped = line.strip()

            # Remove self-assignments: x = x
            if self.eliminate_dead_assignments and self_assign_pattern.match(stripped):
                continue

            closing_count = len(re.findall(r"\b(?:end|until)\b", stripped))
            fn_match = re.search(r"\bfunction\s*(?:[a-zA-Z0-9_.:]+)?\s*\(([^)]*)\)", stripped)
            do_match = re.search(r"\b(?:do|then|repeat)\b", stripped)

            if stripped in ("end", "end;", "until", "end)") or stripped.startswith("end ") or stripped.startswith("until "):
                for _ in range(closing_count):
                    if len(scope_stack) > 1:
                        scope_stack.pop()
                        aliases_dirty = True

            # Check if line defines an alias
            m = copy_pattern.match(stripped)
            if m:
                var_dst, var_src = m.group(1), m.group(2)
                if not var_src.startswith("__EPI_") and not var_dst.startswith("__EPI_"):
                    root_src = resolve_root(var_src)
                    # Only eliminate alias if neither dst nor root_src is reassigned
                    if (
                        assignment_counts.get(root_src, 0) <= 1
                        and assignment_counts.get(var_dst, 0) <= 1
                        and root_src != var_dst
                        and root_src not in LUA_KEYWORDS
                        and var_dst not in LUA_KEYWORDS
                    ):
                        scope_stack[-1]["aliases"][var_dst] = root_src
                        scope_stack[-1]["locals"].add(var_dst)
                        aliases_dirty = True
                        # Drop the redundant alias definition line
                        continue

            m_local = re.match(r"^\s*local\s+([a-zA-Z_][a-zA-Z0-9_,\s]*)", stripped)
            if m_local and not stripped.startswith("local function"):
                for v in m_local.group(1).split(","):
                    v_clean = v.split(":")[0].strip().split("=")[0].strip()
                    if v_clean:
                        scope_stack[-1]["locals"].add(v_clean)
                        aliases_dirty = True

            # Apply active aliases to line
            if aliases_dirty:
                rebuild_active_aliases()

            transformed_line = line
            if active_aliases:
                words = set(_RE_IDENT.findall(line))
                matching = words.intersection(active_aliases.keys())
                if matching:
                    for var in sorted(matching, key=len, reverse=True):
                        transformed_line = _get_alias_sub_pattern(var).sub(active_aliases[var], transformed_line)

            cleaned_lines.append(transformed_line)

            if fn_match:
                params = {p.strip().split(":")[0].strip() for p in fn_match.group(1).split(",") if p.strip()}
                scope_stack.append({"aliases": {}, "locals": params})
                aliases_dirty = True
            elif do_match and not stripped.startswith("end"):
                scope_stack.append({"aliases": {}, "locals": set()})
                aliases_dirty = True

        return cleaned_lines

    def optimize(self, lua_code: str) -> str:
        """
        Full optimization pipeline on Lua source code string.
        Guarantees string literals and comments are never mutated.
        """
        tokens = split_lua_tokens(lua_code)

        # Fold Prometheus string concatenations: "chunk1" .. "chunk2"
        if self.fold_strings:
            tokens = fold_string_concat_tokens(tokens)

        # Mask strings and comments with a collision-free prefix
        while True:
            prefix = f"__EPI_{uuid.uuid4().hex[:8]}_"
            if prefix not in lua_code:
                break

        masked_parts = []
        mapping: Dict[str, str] = {}
        str_counter = 0
        cmt_counter = 0

        for token_type, content in tokens:
            if token_type in ("STRING_SHORT", "STRING_LONG"):
                placeholder = f"{prefix}STR_{str_counter}__"
                str_counter += 1
                mapping[placeholder] = content
                masked_parts.append(placeholder)
            elif token_type == "COMMENT_SHORT":
                placeholder = f"--{prefix}CMT_{cmt_counter}__"
                cmt_counter += 1
                mapping[placeholder] = content
                masked_parts.append(placeholder)
            elif token_type == "COMMENT_LONG":
                placeholder = f"--[[{prefix}CMTL_{cmt_counter}__]]"
                cmt_counter += 1
                mapping[placeholder] = content
                masked_parts.append(placeholder)
            else:
                chunk = content
                if self.fold_constants:
                    chunk = self.fold_math_expressions(chunk)
                masked_parts.append(chunk)

        masked = "".join(masked_parts)

        # Fold table.concat calls: table.concat({"a", "b", "c"}) -> "abc"
        if self.fold_strings:
            masked = fold_table_concat_calls(masked, mapping, prefix)

        # Strip Prometheus watermark checks
        if self.strip_watermarks:
            masked = strip_prometheus_watermarks(masked, mapping, prefix)

        # Line-by-line post-passes (alias propagation, dead code, blank lines)
        lines = masked.splitlines()
        if self.propagate_copies or self.eliminate_dead_assignments:
            lines = self.propagate_copy_assignments(lines)

        # Normalize redundant blank lines (max 2 consecutive)
        final_lines = []
        consecutive_blank = 0
        for line in lines:
            if not line.strip():
                consecutive_blank += 1
                if consecutive_blank <= 1:
                    final_lines.append("")
            else:
                consecutive_blank = 0
                final_lines.append(line)

        unmasked = "\n".join(final_lines) + "\n"

        # Restore strings and comments in a single pass
        sample_key = next(iter(mapping.keys()), None)
        if sample_key:
            m_pref = re.search(r"(__EPI_[0-9a-fA-F]+_)", sample_key)
            if m_pref:
                p_esc = re.escape(m_pref.group(1))
                pattern = re.compile(rf"--\[\[{p_esc}CMTL_\d+__\]\]|--{p_esc}CMT_\d+__|{p_esc}STR_\d+__")
                unmasked = pattern.sub(lambda m: mapping.get(m.group(0), m.group(0)), unmasked)
            else:
                for placeholder, original in sorted(mapping.items(), key=lambda kv: len(kv[0]), reverse=True):
                    unmasked = unmasked.replace(placeholder, original)

        return unmasked


def optimize_lua_code(lua_code: str) -> str:
    """Convenience function for optimizing Lua source."""
    opt = AstOptimizer()
    return opt.optimize(lua_code)
